name: receipt_scanner
description: A Flutter app for receipt/document edge detection and cropping using YOLOv8 + Cubic Polynomial.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  tflite_flutter: ^0.11.0
  image: ^4.3.0
  path_provider: ^2.1.4
  path: ^1.9.0
  permission_handler: ^11.3.1
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
